import type { Metadata } from "next";
import { Geist, Geist_Mono, Literata } from "next/font/google";
import "./globals.css";

/* ===== FONTS ===== */

// Geist Sans (UI)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Geist Mono (Code)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Literata (Hero / Banner typography)
const literata = Literata({
  variable: "--font-literata",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
  display: "swap",
});

/* ===== METADATA ===== */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* ===== ROOT LAYOUT ===== */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${literata.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
